INSERT INTO WEATHERCAT (DESCRIPTION) VALUES ('Sunny');
INSERT INTO WEATHERCAT (DESCRIPTION) VALUES ('Rain');
INSERT INTO WEATHERCAT (DESCRIPTION) VALUES ('Snow');
INSERT INTO WEATHERCAT (DESCRIPTION) VALUES ('Windy');
INSERT INTO WEATHERCAT (DESCRIPTION) VALUES ('Sleet');

INSERT INTO DEPARTMENT (DESCRIPTION) VALUES ('Women');
INSERT INTO DEPARTMENT (DESCRIPTION) VALUES ('Men');
INSERT INTO DEPARTMENT (DESCRIPTION) VALUES ('Kids');
INSERT INTO DEPARTMENT (DESCRIPTION) VALUES ('H&M Home');
INSERT INTO DEPARTMENT (DESCRIPTION) VALUES ('Sport');
INSERT INTO DEPARTMENT (DESCRIPTION) VALUES ('Accessories');

INSERT INTO SEASON (DESCRIPTION) VALUES ('Summer');
INSERT INTO SEASON (DESCRIPTION) VALUES ('Winter');
INSERT INTO SEASON (DESCRIPTION) VALUES ('Spring');
INSERT INTO SEASON (DESCRIPTION) VALUES ('Autumn');

INSERT INTO SEASONPERCOUNTRY (COUNTRYID,SEASONID,DATEFROM,DATETO) VALUES ('SE',1,'2020-06-01','2020-08-31');
INSERT INTO SEASONPERCOUNTRY (COUNTRYID,SEASONID,DATEFROM,DATETO) VALUES ('SE',2,'2020-12-01','2020-03-31');
INSERT INTO SEASONPERCOUNTRY (COUNTRYID,SEASONID,DATEFROM,DATETO) VALUES ('SE',3,'2020-04-01','2020-05-31');
INSERT INTO SEASONPERCOUNTRY (COUNTRYID,SEASONID,DATEFROM,DATETO) VALUES ('SE',4,'2020-09-01','2020-11-30');

INSERT INTO PRODUCT (ID,WEATHERCATID,DEPARTMENTID,SEASONID,IMAGE,IMAGESIZE,URL) VALUES (0769483005,1,2,1,'https://lp2.hm.com/hmgoepprod?set=source[/21/f8/21f8033ed4cd662d8e4464abbab57bd353de12dc.jpg],origin[dam],category[men_swimweear],type[LOOKBOOK],res[z],hmver[1]&call=url[file:/product/main]',1,'https://www2.hm.com/sv_se/productpage.0769483005.html');