CREATE TABLE PRODUCTS (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  WEATHERCATID BIGINT NOT NULL,
  DEPARTMENTID BIGINT NOT NULL,
  SEASONID BIGINT NOT NULL,
  IMAGE VARCHAR(500),
  IMAGESIZE BIGINT NOT NULL,
  URL VARCHAR(500)
 );

 CREATE TABLE WEATHERCAT (
   ID BIGINT AUTO_INCREMENT PRIMARY KEY,
   DESCRIPTION VARCHAR(500)
 );